apiVersion: v1
kind: Namespace
metadata:
  name: agrocarbon360
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: agrocarbon360
data:
  DATABASE_URL: "postgresql://agrocarbon:password@postgres:5432/agrocarbon360"
  JWT_SECRET_KEY: "your-super-secret-jwt-key-change-in-production"
  BLOCKCHAIN_RPC_URL: "https://polygon-rpc.com"
  BLOCKCHAIN_CONTRACT_ADDRESS: "0x1234567890123456789012345678901234567890"
  CARBON_CREDITS_CONTRACT_ADDRESS: "0x1234567890123456789012345678901234567890"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: agrocarbon360
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"
  JWT_SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: agrocarbon360
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "agrocarbon360"
        - name: POSTGRES_USER
          value: "agrocarbon"
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: agrocarbon360
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: agrocarbon360
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: agrocarbon360/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_URL
        - name: JWT_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: JWT_SECRET_KEY
        - name: BLOCKCHAIN_RPC_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: BLOCKCHAIN_RPC_URL
        - name: BLOCKCHAIN_CONTRACT_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: BLOCKCHAIN_CONTRACT_ADDRESS
        - name: CARBON_CREDITS_CONTRACT_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: CARBON_CREDITS_CONTRACT_ADDRESS
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: agrocarbon360
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: agrocarbon360
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: agrocarbon360
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-pipeline
  template:
    metadata:
      labels:
        app: ml-pipeline
    spec:
      containers:
      - name: ml-pipeline
        image: agrocarbon360/ml-pipeline:latest
        env:
        - name: BACKEND_URL
          value: "http://backend:8000"
        - name: GEE_SERVICE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: ml-secrets
              key: gee-service-account
        volumeMounts:
        - name: ml-models
          mountPath: /app/models
        - name: ml-data
          mountPath: /app/data
      volumes:
      - name: ml-models
        persistentVolumeClaim:
          claimName: ml-models-pvc
      - name: ml-data
        persistentVolumeClaim:
          claimName: ml-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-models-pvc
  namespace: agrocarbon360
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-data-pvc
  namespace: agrocarbon360
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-server
  namespace: agrocarbon360
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-server
  template:
    metadata:
      labels:
        app: fl-server
    spec:
      containers:
      - name: fl-server
        image: agrocarbon360/fl-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_URL
          value: "http://backend:8000"
        - name: FL_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: fl-server
  namespace: agrocarbon360
spec:
  selector:
    app: fl-server
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agrocarbon360-ingress
  namespace: agrocarbon360
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.agrocarbon360.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
  - host: fl.agrocarbon360.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fl-server
            port:
              number: 8080
